import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Box, Check, CheckCheck, ChevronRight, CircleHelp, Download, Eye, Hand, Home, Lightbulb, LoaderCircle, Pause, Play, Redo2, RotateCcw, RotateCw, Settings, ShieldCheck, Shuffle, Sparkles, Target, Timer, Trophy, Undo2, Upload, Volume2, VolumeX, WifiOff, X } from 'lucide-react';
import { CubeScene } from './components/CubeScene';
import { applyMoves, inverse, isSolved, SOLVED, scramble, goalReached, describeMove } from './cube/engine';
import { solveState } from './cube/solver';
import { lessons, getLesson, lessonStage, lessonStageCount, lessonCheckpoint, lessonStagePrefix, lessonStageContinuation, lessonHighlights } from './content/lessons';
import { defaultData, loadData, saveData, parseBackup, serializeBackup, requestPersistentStorage } from './lib/storage';
import type { AppData, Activity } from './lib/storage';
import { narration } from './lib/audio';
import { beginCubeTransition, historyTransition } from './lib/interaction';
import { registerOffline, verifyOffline, applyUpdate } from './lib/offline';
import { readScreen, writeScreen, type Screen } from './lib/routes';

const faces=[{id:'U',name:'Sus',color:'#f5ca3c'},{id:'R',name:'Dreapta',color:'#ed575e'},{id:'F',name:'Față',color:'#23b99c'},{id:'D',name:'Jos',color:'#f9fafb'},{id:'L',name:'Stânga',color:'#ff9441'},{id:'B',name:'Spate',color:'#387bea'}];
const movesOf=(alg:string)=>alg.trim().split(/\s+/).filter(Boolean);
const sessionId=crypto.randomUUID();
const clock=(ms:number)=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
const faceName=(move:string)=>faces.find(f=>f.id===move[0])?.name.toLowerCase()||'';
const moveText=describeMove;
function activity(mode:Activity['mode'],lessonId?:string):Activity{
 const lesson=lessonId?getLesson(lessonId):undefined;
 const setup=mode==='free'?scramble(20):(lesson?.setup||'');
 const initial=applyMoves(SOLVED,setup);
 return {mode,lessonId,phase:mode==='free'?'practice':mode==='physical'?'physical-orient':'intro',state:mode==='physical'?SOLVED:initial,initial,moves:[],cursor:0,assisted:false,step:0,demoIndex:0,physicalSetupIndex:0,timerMs:0,timerRunning:false,timerInterrupted:false,startedAt:Date.now()};
}
export default function App(){
 const [data,setData]=useState<AppData>(defaultData); const dataRef=useRef(data);dataRef.current=data;
 const [loaded,setLoaded]=useState(false),[storageReady,setStorageReady]=useState(false),[screen,setScreen]=useState<Screen>(()=>readScreen()),[face,setFace]=useState('R'),[view,setView]=useState(false),[resetView,setResetView]=useState(0);
 const [lastMove,setLastMove]=useState<{move:string,id:number}>(),[busy,setBusy]=useState(false),[hint,setHint]=useState<{state:string,move:string,text:string}|null>(null),[thinking,setThinking]=useState(false),[notice,setNotice]=useState('');
 const [modal,setModal]=useState<{title:string,text:string,action:()=>void,label:string}|null>(null),[help,setHelp]=useState(false),[parentOpen,setParentOpen]=useState(false),[parentAnswer,setParentAnswer]=useState('');
 const [backupDownload,setBackupDownload]=useState<{href:string,filename:string}|null>(null),[backupError,setBackupError]=useState('');
 const [offline,setOffline]=useState(false),[online,setOnline]=useState(navigator.onLine),[update,setUpdate]=useState(false),[storageError,setStorageError]=useState(''),[audioStatus,setAudioStatus]=useState('');
 const lock=useRef(false),demoToken=useRef(0),fileInput=useRef<HTMLInputElement>(null),saveChain=useRef(Promise.resolve()),hintToken=useRef(0);
 const current=data.active;const lesson=current?.lessonId?getLesson(current.lessonId):undefined;
 const totalLearned=new Set(data.attempts.filter(a=>!a.physical).map(a=>a.lessonId)).size;
 const mastered=(id:string)=>new Set(data.attempts.filter(a=>a.lessonId===id&&!a.assisted&&!a.physical).map(a=>a.sessionId)).size>=2;
 const edit=useCallback((f:(d:AppData)=>AppData)=>setData(d=>f(d)),[]);
 const changeActive=useCallback((f:(a:Activity)=>Activity)=>edit(d=>d.active?{...d,active:f(d.active)}:d),[edit]);
 useEffect(()=>{loadData().then(d=>{if(d.active){d.active.timerInterrupted ||= d.active.timerRunning; d.active.timerRunning=false;if(d.active.phase==='watch')d.active.phase='demo-paused';if(d.active.mode==='physical'&&!['physical-orient','complete'].includes(d.active.phase))d.active.phase='physical-resume'}const route=readScreen(),next=route==='session'&&!d.active?'home':route;writeScreen(next,true);setScreen(next);setData({...d,lastScreen:next});setStorageReady(true);setLoaded(true)}).catch(e=>{setStorageError(String(e));if(readScreen()==='session'){writeScreen('home',true);setScreen('home')}setLoaded(true)});registerOffline(()=>setOffline(true),()=>setUpdate(true),()=>setOffline(false));const on=()=>setOnline(navigator.onLine);window.addEventListener('online',on);window.addEventListener('offline',on);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',on);narration.stop()}},[]);
 useEffect(()=>{if(!loaded||!storageReady)return;saveChain.current=saveChain.current.catch(()=>{}).then(()=>saveData(data)).catch(e=>setStorageError(`Progresul nu s-a putut salva: ${String(e)}`))},[data,loaded,storageReady]);
 useEffect(()=>{
  if(!parentOpen||screen!=='parents'){setBackupDownload(null);return;}
  let href:string|undefined;
  try{
   // Prepare the latest validated in-memory snapshot before a trusted click.
   // The native download link must not await IndexedDB or synthesize a click.
   href=URL.createObjectURL(new Blob([serializeBackup(data)],{type:'application/json'}));
   setBackupDownload({href,filename:`cubul-lui-erik-${new Date().toISOString().slice(0,10)}.json`});
   setBackupError('');
  }catch(error){setBackupDownload(null);setBackupError(`Copia de siguranță nu a putut fi pregătită. ${String(error)}`);}
  return()=>{if(href)URL.revokeObjectURL(href);};
 },[data,parentOpen,screen]);
 useEffect(()=>{setHint(null);hintToken.current++;if(current?.phase!=='watch')narration.stop()},[current?.state,current?.mode,current?.lessonId,current?.step]);
 useEffect(()=>{const hide=()=>{if(document.hidden){demoToken.current++;lock.current=false;setBusy(false);narration.stop();changeActive(a=>({...a,phase:a.phase==='watch'?'demo-paused':a.phase,timerInterrupted:a.timerInterrupted||a.timerRunning,timerRunning:false}))}};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[changeActive]);
 useEffect(()=>{if(!current?.timerRunning)return;let last=performance.now();const id=window.setInterval(()=>{const now=performance.now(),elapsed=now-last;last=now;changeActive(a=>({...a,timerMs:a.timerMs+elapsed}))},250);return()=>clearInterval(id)},[current?.timerRunning,changeActive]);
 const speak=async(text:string,key?:string)=>{if(dataRef.current.preferences.muted){narration.stop();return 'ended'}const result=await narration.speak(text,key,dataRef.current.preferences.slow);if(result!=='cancelled')setAudioStatus(result==='unavailable'?'Vocea română nu este disponibilă aici. Poți urma toate instrucțiunile de pe ecran.':'');return result};
 const go=useCallback((requested:Screen,fromHistory=false)=>{const next=requested==='session'&&!dataRef.current.active?'home':requested;demoToken.current++;hintToken.current++;lock.current=false;setBusy(false);setThinking(false);narration.stop();setNotice('');setHint(null);setModal(null);setHelp(false);writeScreen(next,fromHistory);setScreen(next);edit(d=>({...d,lastScreen:next,active:d.active?{...d.active,phase:d.active.phase==='watch'?'demo-paused':next==='session'&&d.active.mode==='physical'&&d.active.phase!=='complete'?'physical-resume':d.active.phase,timerRunning:false,timerInterrupted:d.active.timerInterrupted||d.active.timerRunning}:null}));window.scrollTo(0,0)},[edit]);
 useEffect(()=>{const backOrForward=()=>go(readScreen(),true);window.addEventListener('popstate',backOrForward);return()=>window.removeEventListener('popstate',backOrForward)},[go]);
 function start(mode:Activity['mode'],id?:string){const run=()=>{demoToken.current++;hintToken.current++;narration.stop();lock.current=false;setBusy(false);setThinking(false);setData(d=>({...d,active:activity(mode,id),lastScreen:'session'}));setFace('R');setView(false);setResetView(x=>x+1);writeScreen('session');setScreen('session');setNotice('');setHint(null);window.scrollTo(0,0)};if(current&&current.phase!=='complete'&&(current.cursor>0||current.mode==='physical'))setModal({title:'Începem o activitate nouă?',text:'Progresul lecțiilor rămâne salvat. Poziția activității curente va fi înlocuită.',label:'Da, începem',action:run});else run()}
 function complete(a:Activity,d:AppData):AppData{
  const interrupted=a.timerInterrupted||(a.timerMs>0&&!a.timerRunning);
  const next={...a,phase:'complete',timerRunning:false,timerInterrupted:interrupted};
  if(a.mode==='free')return{...d,active:next,solves:[...d.solves,{at:Date.now(),durationMs:a.timerMs,physical:false,assisted:a.assisted,interrupted}]};
  return{...d,active:next,solves:a.mode==='physical'&&getLesson(a.lessonId)?.steps?[...d.solves,{at:Date.now(),durationMs:a.timerMs,physical:true,assisted:true,interrupted}]:d.solves,attempts:[...d.attempts,{lessonId:a.lessonId!,at:Date.now(),assisted:a.assisted||a.phase!=='independent',physical:a.mode==='physical',sessionId}]};
 }
 function toggleTimer(){changeActive(a=>({...a,timerRunning:!a.timerRunning,timerInterrupted:a.timerInterrupted||a.timerRunning||a.cursor>0||(a.mode==='physical'&&a.demoIndex>0)}));}
 function turn(move:string){
  const active=dataRef.current.active;
  if(!active||active.mode==='physical'||!['practice','independent'].includes(active.phase)||!beginCubeTransition(lock,setBusy,()=>dataRef.current.active?.phase==='watch'))return;
  narration.stop();hintToken.current++;setHint(null);setNotice('');setLastMove({move,id:Date.now()});
  edit(d=>{if(!d.active)return d;let a={...d.active,state:applyMoves(d.active.state,move),moves:[...d.active.moves.slice(0,d.active.cursor),move],cursor:d.active.cursor+1};
   const l=a.lessonId?getLesson(a.lessonId):undefined;const g=l?.steps?.[a.step]?.goal||l?.goal;
   if(a.mode==='free'?isSolved(a.state):g&&goalReached(a.state,g)){
    if(l?.steps&&a.step<l.steps.length-1&&!isSolved(a.state))a={...a,phase:'stage-done'};else return complete(a,d);
   }
   return{...d,active:a};});
 }
 function history(delta:number){
  const active=dataRef.current.active,transition=active?historyTransition(active,delta):null;
  if(!transition||!beginCubeTransition(lock,setBusy,()=>dataRef.current.active?.phase==='watch'))return;
  narration.stop();hintToken.current++;setHint(null);setNotice('');setLastMove({move:transition.move,id:Date.now()});
  changeActive(a=>{const next=historyTransition(a,delta)?.activity||a;const l=getLesson(next.lessonId);if(l?.steps){let step=0;while(step<l.steps.length-1&&goalReached(next.state,l.steps[step].goal))step++;return{...next,step};}return next;});
 }
 function restart(independent=false){narration.stop();demoToken.current++;changeActive(a=>({...a,state:a.initial,moves:[],cursor:0,phase:independent?'independent':'practice',assisted:current?.mode==='learn'&&!independent,step:0,demoIndex:0,timerMs:0,timerRunning:false,timerInterrupted:false}));setHint(null);setNotice('');}
 function restoreStage(){if(!lesson||!current)return;const prefix=lessonStagePrefix(lesson,current.step);changeActive(a=>({...a,state:lessonCheckpoint(lesson,a.step),moves:prefix,cursor:prefix.length,phase:'practice',assisted:true,demoIndex:0}));setHint(null);setNotice('');}
 function nextStage(){if(!lesson||!current||current.step>=lessonStageCount(lesson)-1)return;let step=current.step+1;while(step<lessonStageCount(lesson)-1&&goalReached(current.state,lessonStage(lesson,step).goal))step++;changeActive(a=>({...a,step,phase:a.assisted?'practice':'independent'}));setNotice('');}
 async function demonstrate(){if(!lesson||!current||lock.current)return;const token=++demoToken.current,stage=lessonStage(lesson,current.step),prefix=lessonStagePrefix(lesson,current.step);lock.current=true;setBusy(true);narration.stop();changeActive(a=>({...a,phase:'watch',state:lessonCheckpoint(lesson,a.step),demoIndex:0,moves:prefix,cursor:prefix.length,assisted:true}));setNotice(stage.text);await speak(stage.text,lesson.steps?`${lesson.id}-step-${current.step}`:lesson.id);if(token!==demoToken.current)return;
  const alg=movesOf(stage.moves);for(let i=0;i<alg.length;i++){if(token!==demoToken.current)return;setFace(alg[i][0]);setNotice(moveText(alg[i]));await speak(moveText(alg[i]),`move-${alg[i].replace("'",'-prime')}`);if(token!==demoToken.current)return;setLastMove({move:alg[i],id:Date.now()});changeActive(a=>({...a,state:applyMoves(a.state,alg[i]),demoIndex:i+1}));await new Promise(r=>setTimeout(r,dataRef.current.preferences.slow?950:550));}
  if(token===demoToken.current){changeActive(a=>({...a,phase:'demo-done'}));setNotice('Ai văzut cum funcționează. Acum revenim la poziția de început a etapei, ca să încerci tu.');lock.current=false;setBusy(false)}
 }
 function pauseDemo(){demoToken.current++;narration.stop();lock.current=false;setBusy(false);changeActive(a=>({...a,phase:'demo-paused'}));}
 async function requestHint(){if(!current||thinking)return;const snapshot=current.state,token=++hintToken.current;changeActive(a=>({...a,assisted:true}));setThinking(true);setNotice('');
  try{let suggested:string|undefined;let text='Ajutor de mișcare pentru poziția de acum. Acesta este un pas calculat spre cubul rezolvat, nu o explicație CFOP.';
   if(lesson){const remaining=lessonStageContinuation(lesson,current.step,snapshot);suggested=remaining?.[0];if(suggested)text=lesson.steps?.[current.step]?.text||lesson.hint;}
   if(!suggested){const answer=await solveState(snapshot);suggested=answer[0];}
   if(token!==hintToken.current||dataRef.current.active?.state!==snapshot)return;
   if(suggested){setHint({state:snapshot,move:suggested,text});setFace(suggested[0]);}else setNotice('Cubul este deja rezolvat.');
  }catch{setNotice('Ajutorul nu a putut fi calculat. Poți folosi Înapoi sau relua exercițiul.')}finally{setThinking(false)}
 }
 function physicalAdvance(){if(!current||!lesson||!beginCubeTransition(lock,setBusy,()=>false))return;const isSetup=current.phase==='physical-setup';const alg=movesOf(isSetup?lesson.setup:lesson.solution);const idx=isSetup?current.physicalSetupIndex:current.demoIndex;
  if(idx<alg.length){setLastMove({move:alg[idx],id:Date.now()});changeActive(a=>({...a,state:applyMoves(a.state,alg[idx]),physicalSetupIndex:isSetup?idx+1:a.physicalSetupIndex,demoIndex:isSetup?a.demoIndex:idx+1}));}
  else if(isSetup)changeActive(a=>({...a,phase:'physical-do',demoIndex:0}));else edit(d=>d.active?complete(d.active,d):d);
 }
 function physicalBack(){if(!current||!lesson)return;const setup=current.phase==='physical-setup',idx=setup?current.physicalSetupIndex:current.demoIndex;if(!idx)return;const alg=movesOf(setup?lesson.setup:lesson.solution),move=inverse(alg[idx-1]);setModal({title:`Fă pe cubul tău: ${move}`,text:`${moveText(move)} Apasă doar după ce ai făcut mișcarea inversă pe cubul real.`,label:'Am făcut mișcarea inversă',action:()=>{setLastMove({move,id:Date.now()});changeActive(a=>({...a,state:applyMoves(a.state,move),physicalSetupIndex:setup?idx-1:a.physicalSetupIndex,demoIndex:setup?a.demoIndex:idx-1}));}})}
 const resume=()=>{if(current){if(current.mode==='physical'&&current.phase!=='complete')changeActive(a=>({...a,phase:'physical-resume'}));go('session')}else start('learn',lessons.find(l=>!l.optional)?.id||lessons[0].id)};
 const pref=(key:keyof AppData['preferences'])=>{if(key==='muted')narration.stop();edit(d=>({...d,preferences:{...d.preferences,[key]:!d.preferences[key]}}))};
 async function importBackup(file:File){try{if(file.size>5000000)throw Error('Fișierul este prea mare.');const imported=parseBackup(await file.text());setModal({title:'Restaurăm copia de siguranță?',text:'Progresul de pe acest dispozitiv va fi înlocuit cu cel din fișier. Exportă mai întâi o copie dacă vrei să-l păstrezi.',label:'Restaurează progresul',action:()=>{if(imported.active){imported.active.timerRunning=false;imported.active.timerInterrupted=true;if(imported.active.phase==='watch')imported.active.phase='demo-paused';}setStorageReady(true);setData(imported);setNotice('Copia de siguranță a fost restaurată.')}})}catch(e){setNotice(`Fișierul nu este valid. ${String(e)}`)}}
 const nav=[{id:'home',label:'Acasă',icon:Home},{id:'lessons',label:'Învață',icon:BookOpen},{id:'play',label:'Exersează',icon:Box},{id:'progress',label:'Progres',icon:Trophy}];
 const activeLesson=lesson?.steps?.[current?.step||0];
 const stageMoveCount=lesson?movesOf(lessonStage(lesson,current?.step||0).moves).length:0;
 const offLessonPath=!!(lesson&&current&&['practice','independent'].includes(current.phase)&&lessonStageContinuation(lesson,current.step,current.state)===null);
 let physicalStep=0,physicalPrior=0;if(lesson?.steps&&current?.mode==='physical'){for(let i=0;i<lesson.steps.length;i++){const length=movesOf(lesson.steps[i].moves).length;if(current.demoIndex<physicalPrior+length){physicalStep=i;break;}physicalPrior+=length;physicalStep=i;}}
 const physicalText=lesson?.steps?.[physicalStep]?.text||lesson?.explanation||'';
 const subtitle=current?.mode==='free'?'Rezolvă singur':current?.mode==='physical'?'Cu cubul meu':'Învață cu mine';
 const physicalAlg=lesson?movesOf(current?.phase==='physical-setup'?lesson.setup:lesson.solution):[];
 const physicalIdx=current?.phase==='physical-setup'?current.physicalSetupIndex:current?.demoIndex||0;
 const phase=current?.phase||'';
 const faceLabel=faces.find(f=>f.id===face)!;
 const currentText=notice||(current?.mode==='free'?'Alege o față. Întoarce-o. Găsește-ți propriul drum.':offLessonPath?'Poziția ta este diferită de exemplu. Poți continua pe drumul tău, cere un indiciu pentru cubul de acum sau reveni la exemplul etapei.':activeLesson?.text||lesson?.explanation||'');
 if(!loaded)return <div className="loading"><div className="brand-icon"><Box/></div><h2>Pregătim cubul…</h2><LoaderCircle className="spin"/></div>;
 return <div className="app-shell">
  <header className="topbar"><button className="brand" onClick={()=>go('home')} aria-label="Cubul lui Erik — acasă"><span className="brand-icon"><Box size={25}/></span><span>Cubul lui <b>Erik</b><small>UN PAS MIC. UN SUPERPROGRES.</small></span></button><div className="top-actions"><span className={`connection ${!online?'disconnected':''}`}>{!online?<WifiOff size={14}/>:<span className="tiny-dot"/>}{!online?'Offline':offline?'Gata de aventură':'Bine ai venit'}</span><button className="icon-button" aria-label="Pentru părinți" onClick={()=>go('parents')}><Settings size={21}/></button><div className="avatar" aria-label="Erik">E</div></div></header>
  {storageError&&<div className="error-banner" role="alert">{storageError} Descarcă o copie din „Pentru părinți”.</div>}
  <main className={screen==='session'?'session-main':''}>
  {screen==='home'&&<>
   <div className="greeting"><div><span className="eyebrow"><Sparkles size={15}/> MICUL TĂU ATELIER DE CUBURI</span><h1>Salut, Erik<span className="blue">.</span></h1><p>Un pic de curiozitate. Câteva mișcări. Tot mai bun.</p></div><div className="journey-count"><span><BookOpen size={20}/></span><div><strong>{totalLearned} <small>/ {lessons.length}</small></strong><small>lecții încercate</small></div></div></div>
   <section className="hero-card"><div className="hero-copy"><span className="pill"><span className="tiny-dot"/> {current?'AVENTURA CONTINUĂ':'URMĂTORUL TĂU PAS'}</span><h2>{current?(lesson?.title||'Cubul tău te așteaptă.'):'Două piese.\nO echipă perfectă.'}</h2><p>{current?'Am păstrat locul în care ai rămas. Hai să continuăm!':'Știi deja să rezolvi cubul. Acum descoperim cum se unesc colțurile cu muchiile.'}</p><button className="primary hero-button" onClick={resume}><Play size={19} fill="currentColor"/>Continuă<ArrowRight size={20}/></button><span className="small-caption">{current?'Exact de unde ai rămas':'F2L intuitiv · 3–5 minute · În ritmul tău'}</span></div><div className="hero-stage"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="cube-caption"><span className="tiny-dot"/> Hai să le potrivim.</span><CubeScene state={current?.state||applyMoves(SOLVED,"R U R'")} compact disabled/><div className="stage-note"><span className="note-symbol"><Check size={16}/></span>Fiecare mișcare are un rost.</div></div></section>
   <section className="mode-section"><div className="section-heading"><h2>Cum exersăm azi?</h2><span>Tu alegi ritmul.</span></div><div className="mode-grid"><button className="mode-card" onClick={()=>go('lessons')}><span className="mode-icon blue-bg"><BookOpen/></span><h3>Învață cu mine</h3><p>Privește, înțelege, apoi încearcă tu.</p><span className="card-link">Descoperă lecțiile <ArrowRight size={18}/></span></button><button className="mode-card" onClick={()=>start('free')}><span className="mode-icon teal-bg"><Box/></span><h3>Rezolvă singur</h3><p>Cubul tău, mișcările tale. Ajutor la un pas.</p><span className="card-link">Deschide cubul <ArrowRight size={18}/></span></button><button className="mode-card" onClick={()=>go('physical')}><span className="mode-icon peach-bg"><Hand/></span><h3>Cu cubul meu</h3><p>Ia cubul în mâini. Te ghidăm pas cu pas.</p><span className="card-link">Exersează pe bune <ArrowRight size={18}/></span></button></div></section>
   <div className="gentle-tip"><span className="tip-icon"><Lightbulb size={23}/></span><div><strong>Mai întâi înțelegem. Apoi prindem viteză.</strong><p>Mișcările noi pot părea mai lente la început. E o parte firească din învățare.</p></div></div>
  </>}
  {(screen==='lessons'||screen==='physical')&&<><button className="back-link" onClick={()=>go('home')}><ArrowLeft size={17}/>Înapoi acasă</button><div className="page-heading"><span className="eyebrow">{screen==='physical'?'ÎN MÂINILE TALE':'PAS CU PAS, TOT MAI BUN'}</span><h1>{screen==='physical'?'Ia-ți cubul. Hai să exersăm.':'Micile tale descoperiri.'}</h1><p>{screen==='physical'?'Pornim de la un cub rezolvat. Tu faci mișcările și ne spui când ești gata.':'Lecții scurte. Idei clare. Alege ceva nou sau repetă ce ai descoperit.'}</p></div><div className="course-intro"><Target/><p><strong>Drumul spre CFOP</strong><span>Cruce → perechi F2L → fața de sus (OLL) → ultimele piese (PLL)</span></p><span className="pill">{lessons.length} lecții</span></div><div className="lesson-grid">{lessons.map((l,i)=>{const tried=data.attempts.some(a=>a.lessonId===l.id);return <button key={l.id} className={`lesson-card ${tried?'attempted':''}`} onClick={()=>start(screen==='physical'?'physical':'learn',l.id)}><div className="lesson-top"><span className="lesson-number">{String(i+1).padStart(2,'0')}</span><span className="category">{l.category}</span>{tried&&<CheckCheck size={21} className="teal"/>}</div><h3>{l.title}</h3><p>{l.subtitle}</p><div className="lesson-meta"><span>{l.duration}{l.optional?' · Opțional':''}</span><span>{mastered(l.id)?'Stăpânit':tried?'Repetă':'Hai să începem'} <ArrowRight size={16}/></span></div></button>})}</div><div className="gentle-tip"><Sparkles/><p>După acest curs: mai multe cazuri PLL, apoi OLL complet și urmărirea următoarei perechi. Le învățăm treptat.</p></div></>}
  {screen==='session'&&current&&<>
   <div className="session-heading"><button className="icon-button" aria-label="Înapoi acasă" onClick={()=>go('home')}><ArrowLeft/></button><div><span className="eyebrow">{subtitle}</span><h1>{current.mode==='free'?'Un cub. Posibilități infinite.':lesson?.title}</h1></div><button className="icon-button audio-button" aria-label={data.preferences.muted?'Pornește sunetul':'Oprește sunetul'} onClick={()=>pref('muted')}>{data.preferences.muted?<VolumeX/>:<Volume2/>}</button></div>
   {phase==='complete'?<div className="completion"><div className="achievement"><Trophy size={48}/></div><span className="eyebrow">ÎNCĂ O MICĂ VICTORIE</span><h2>Ai reușit, Erik!</h2><p>{current.mode==='physical'?'Ai confirmat exercițiul cu cubul tău. Bravo pentru răbdare!':current.mode==='free'?'Fiecare piesă este la locul ei. Tu ai făcut asta!':current.assisted?'Ai descoperit cum funcționează. Încearcă acum fără ajutor.':'Ai găsit drumul. Fiecare încercare te ajută să înțelegi mai bine.'}</p><div className="completion-cube"><CubeScene state={current.state} compact disabled/></div><div className="completion-stats"><span><strong>{current.cursor}</strong>mișcări pe ecran</span><span><strong>{current.mode==='physical'?'Cu cubul real':current.assisted?'Cu ajutor':'Prin practică'}</strong>{current.timerInterrupted?'Cronometrare întreruptă':current.mode==='free'&&data.preferences.timer?clock(current.timerMs):'În ritmul tău'}</span></div><button className="primary" onClick={()=>current.mode==='free'?start('free'):current.mode==='physical'?start('physical',lesson!.id):restart(true)}>{current.mode==='learn'?'Încerc singur':'Mai încerc o dată'}<ArrowRight size={19}/></button><button className="text-button" onClick={()=>go('lessons')}>Alege următoarea lecție</button></div>:<div className="practice-layout">
    <section className="cube-panel"><div className="cube-panel-top"><span className="pill"><span className="tiny-dot"/>{current.mode==='physical'?'Model pentru cubul tău':phase==='watch'?'Privește demonstrația':view?'Privește cubul':'Cubul tău interactiv'}</span>{data.preferences.timer&&(current.mode==='free'||current.mode==='physical')&&<button className={`timer-button ${current.timerRunning?'running':''}`} onClick={toggleTimer}><Timer size={17}/>{clock(current.timerMs)}{current.timerRunning?<Pause size={14}/>:<Play size={14}/>}</button>}</div>
    <CubeScene state={current.state} onMove={turn} selectedFace={face} onSelectFace={setFace} viewMode={view} disabled={busy||(!view&&(current.mode==='physical'||!['practice','independent'].includes(phase)))} highlight={current.mode!=='free'&&lesson?lessonHighlights(lesson,current.state):undefined} lastMove={lastMove} resetViewKey={resetView}/>
    <div className="orientation"><span><i style={{background:'#f5ca3c'}}/>Galben sus</span><span><i style={{background:'#23b99c'}}/>Verde în față</span><span><i style={{background:'#ed575e'}}/>Roșu la dreapta</span></div>
    <div className="view-controls"><button className={view?'selected':''} onClick={()=>setView(v=>!v)}><Eye size={17}/>{view?'Vedere activă':'Privește cubul'}</button><button onClick={()=>{setResetView(x=>x+1);setView(false)}}><RotateCcw size={16}/>Revino la vedere</button></div>
    {current.mode!=='physical'&&<div className={`turn-controls ${!['practice','independent'].includes(phase)?'inactive-controls':''}`}><div className="control-label"><span>Alege fața</span><span>{faceLabel.name} <i style={{background:faceLabel.color}}/></span></div><div className="face-picker">{faces.map(f=><button key={f.id} className={face===f.id?'active':''} aria-label={`Alege fața ${f.name}`} aria-pressed={face===f.id} onClick={()=>{setFace(f.id);setView(false)}}><i style={{background:f.color}}/><span>{f.name}</span></button>)}</div><div className="turn-buttons"><button disabled={busy||!['practice','independent'].includes(phase)} onClick={()=>turn(`${face}'`)} aria-label={`Întoarce ${faceLabel.name} invers`}><RotateCcw/><span>Invers</span><small>{face}'</small></button><button disabled={busy||!['practice','independent'].includes(phase)} onClick={()=>turn(face)} aria-label={`Întoarce ${faceLabel.name} orar`}><RotateCw/><span>Orar</span><small>{face}</small></button><button disabled={busy||!['practice','independent'].includes(phase)} onClick={()=>turn(`${face}2`)} aria-label={`Întoarce ${faceLabel.name} de două ori`}><span className="half-turn">2×</span><span>Jumătate</span><small>{face}2</small></button></div><small className="direction-note">Sensul se citește privind direct fața aleasă.</small></div>}
    </section>
    <aside className="coach-panel"><div className="coach-label"><span className="coach-avatar"><Sparkles size={20}/></span><div><strong>{current.mode==='free'?'În ritmul tău':'Hai să descoperim'}</strong><small>{current.mode==='free'?'Poți cere ajutor oricând':current.mode==='physical'?'Tu miști cubul real':'O singură idee. Pas cu pas.'}</small></div></div>
    {current.mode==='physical'?<>
     {['physical-orient','physical-resume'].includes(phase)?<><span className="step-label">ÎNAINTE SĂ ÎNCEPEM</span><h2>{phase==='physical-resume'?'Cubul tău încă arată la fel?':'Ține cubul ca în imagine.'}</h2><p>{phase==='physical-resume'?'Compară toate fețele. Modelul de pe ecran este salvat, dar aplicația nu poate vedea cubul tău.':'Pornește de la un cub rezolvat: galben sus, verde în față și roșu la dreapta. Păstrează această orientare.'}</p><button className="primary" onClick={()=>changeActive(a=>({...a,phase:a.physicalSetupIndex<movesOf(lesson!.setup).length?'physical-setup':'physical-do'}))}><Check size={19}/>{phase==='physical-resume'?'Da, arată la fel':'Cubul este pregătit'}</button><button className="text-button" onClick={()=>setHelp(true)}>Cubul meu arată altfel</button></>:<><span className="step-label">{phase==='physical-setup'?'PREGĂTIM EXERCIȚIUL':'ACUM EXERSĂM'} · {Math.min(physicalIdx+1,physicalAlg.length)} / {physicalAlg.length}</span><h2>{physicalIdx<physicalAlg.length?moveText(physicalAlg[physicalIdx]).split('. ')[0]:phase==='physical-setup'?'Poziția este pregătită.':'Ai ajuns la rezultat?'}</h2><p>{phase==='physical-setup'?'Fă mișcarea pe cubul tău. Modelul se actualizează doar când apeși „Am făcut”.':physicalText}</p>{physicalIdx<physicalAlg.length&&<div className="move-display"><strong>{physicalAlg[physicalIdx]}</strong><span>{faceName(physicalAlg[physicalIdx])}</span></div>}<button className="primary" disabled={busy} onClick={physicalAdvance}><Check/>{physicalIdx<physicalAlg.length?'Am făcut':phase==='physical-setup'?'Încep exercițiul':'Da, am reușit!'}</button><div className="secondary-row"><button onClick={physicalBack} disabled={physicalIdx===0}><Undo2 size={17}/>Înapoi un pas</button><button onClick={()=>speak(physicalIdx<physicalAlg.length?moveText(physicalAlg[physicalIdx]):lesson!.explanation,physicalIdx<physicalAlg.length?`move-${physicalAlg[physicalIdx].replace("'",'-prime')}`:lesson!.id)}><Volume2 size={17}/>Repetă</button></div><button className="recovery-button" onClick={()=>setHelp(true)}><CircleHelp size={18}/>Cubul meu arată altfel</button>{phase==='physical-do'&&<button className="text-button" onClick={()=>speak(physicalText,lesson?.steps?`${lesson.id}-step-${physicalStep}`:lesson?.id)}><Volume2 size={17}/>Ascultă ideea etapei</button>}<button className="text-button" onClick={()=>pref('timer')}><Timer size={17}/>{data.preferences.timer?'Ascunde timpul':'Cronometru opțional'}</button><small className="physical-disclaimer">Tu confirmi mișcările. Aplicația nu vede cubul real.</small></>}
    </>:<>
     <span className="step-label">{current.mode==='free'?'GĂSEȘTE-ȚI PROPRIUL DRUM':phase==='independent'?'ACUM, FĂRĂ AJUTOR':phase==='intro'?'1. ÎNȚELEGE':phase==='watch'?'2. PRIVEȘTE':phase==='stage-done'?'ETAPĂ REUȘITĂ':'3. ÎNCEARCĂ TU'}</span>
     <h2>{current.mode==='free'?'Pune culorile la locul lor.':phase==='stage-done'?'Foarte bine. Mergem mai departe.':activeLesson?.title||lesson?.subtitle}</h2><p className="coaching-text" aria-live="polite">{currentText}</p>
     {offLessonPath&&<div className="hint-card"><span className="eyebrow"><CircleHelp size={15}/>UN ALT DRUM</span><p>Vrei să urmărim din nou exemplul? Alegerea îți aparține.</p><button className="secondary" disabled={busy} onClick={()=>setModal({title:'Revenim la exemplul etapei?',text:'Poziția și mișcările încercării de acum vor fi înlocuite cu pregătirea acestei etape. Rămâi la aceeași etapă, iar încercarea va fi marcată cu ajutor.',label:'Da, revino la exemplu',action:restoreStage})}><RotateCcw size={17}/>Revino la exemplul etapei</button></div>}
     {phase==='intro'&&<><div className="notice-box"><Target size={19}/><p>{lesson?.notice}</p></div><button className="primary" onClick={demonstrate}><Play size={18} fill="currentColor"/>Arată-mi</button><button className="text-button" onClick={()=>restart(true)}>Știu deja. Încerc singur <ArrowRight size={16}/></button></>}
     {phase==='watch'&&<><div className="demo-progress"><span style={{width:`${current.demoIndex/stageMoveCount*100}%`}}/></div><p className="small-caption">Mișcarea {current.demoIndex} din {stageMoveCount}</p><button className="primary" onClick={pauseDemo}><Pause size={18}/>Pauză</button></>}
     {['demo-done','demo-paused'].includes(phase)&&<><button className="primary" onClick={restoreStage}><Hand size={18}/>Acum încearcă tu</button><p className="small-caption">Butonul readuce vizibil cubul la poziția de început.</p><button className="text-button" onClick={demonstrate}><Play size={17}/>Reia demonstrația de la început</button></>}
     {phase==='stage-done'&&<button className="primary" onClick={nextStage}>Următoarea etapă<ArrowRight size={18}/></button>}
     {['practice','independent'].includes(phase)&&<><div className="notice-box"><Hand size={18}/><p>{current.mode==='free'?'Atinge o față și folosește butoanele. Sau glisează pe ea: spre dreapta pentru orar, spre stânga pentru invers.':lesson?.notice}</p></div>{hint&&hint.state===current.state?<div className="hint-card"><span className="eyebrow"><Lightbulb size={15}/>UN MIC AJUTOR</span><p>{hint.text}</p><p>{moveText(hint.move)}</p><button className="primary" onClick={()=>turn(hint.move)}>Arată următoarea mișcare <strong>{hint.move}</strong></button></div>:<button className="hint-button" onClick={requestHint} disabled={thinking}>{thinking?<LoaderCircle className="spin" size={19}/>:<Lightbulb size={20}/>} {thinking?'Mă uit la poziția ta…':'Un indiciu'}</button>}<div className="secondary-row"><button onClick={()=>history(-1)} disabled={!current.cursor||busy}><Undo2 size={18}/>Înapoi</button><button onClick={()=>history(1)} disabled={current.cursor===current.moves.length||busy}><Redo2 size={18}/>Refă</button></div></>}
     {current.mode==='learn'&&['practice','independent'].includes(phase)&&<button className="text-button demo-again" disabled={busy} onClick={()=>setModal({title:'Vedem din nou etapa?',text:'Demonstrația pornește de la poziția exemplului. Apoi poți relua practica. Încercarea va fi marcată cu ajutor.',label:'Arată-mi etapa',action:demonstrate})}><Play size={16}/>Arată-mi etapa</button>}<div className="audio-tools"><button disabled={phase==='watch'} onClick={()=>speak(currentText,notice||offLessonPath?undefined:activeLesson?`${lesson?.id}-step-${current.step}`:lesson?.id)}><Volume2 size={18}/>Repetă explicația</button><button className={data.preferences.slow?'selected':''} onClick={()=>pref('slow')}>{data.preferences.slow?'0,7×':'1×'} Mai încet</button></div>
     {current.mode==='free'?<div className="session-options"><button onClick={()=>setModal({title:'Amestecăm din nou?',text:'Poziția curentă va fi înlocuită cu o amestecare nouă de 20 de mișcări legale.',label:'Amestecă',action:()=>{setData(d=>({...d,active:activity('free')}));setNotice('')}})}><Shuffle size={17}/>Amestecă</button><button onClick={()=>setModal({title:'Un exercițiu mai ușor?',text:'Începem cu doar trei mișcări, pornind de la un cub rezolvat.',label:'Începe ușor',action:()=>{const initial=applyMoves(SOLVED,"R U F");setData(d=>({...d,active:{...activity('free'),initial,state:initial}}));}})}><Sparkles size={17}/>3 mișcări</button><button onClick={()=>pref('timer')}><Timer size={17}/>{data.preferences.timer?'Ascunde timpul':'Cronometru'}</button></div>:null}
     <div className="session-footer"><button disabled={busy} onClick={()=>setModal({title:'Reluăm de la început?',text:'Cubul revine la poziția de început. Încercarea curentă va fi înlocuită.',label:'Reîncepe',action:()=>restart(current.mode==='learn')} )}><RotateCcw size={16}/>Reîncepe</button><button onClick={()=>setHelp(true)}><CircleHelp size={16}/>Ajutor</button><span>{current.cursor} mișcări</span></div>
    </>}
    {audioStatus&&<p className="audio-status" role="status">{audioStatus}</p>}
    </aside>
   </div>}
  </>}
  {screen==='progress'&&<><div className="page-heading"><span className="eyebrow">FIECARE ÎNCERCARE CONTEAZĂ</span><h1>Uite cât ai descoperit.</h1><p>Înțelegerea vine din practică. Viteza vine după.</p></div><div className="progress-banner"><div className="achievement small"><Trophy size={34}/></div><div><h2>{totalLearned?`${totalLearned} lecții explorate. Bravo!`:'Primul tău pas te așteaptă.'}</h2><p>{data.attempts.filter(a=>!a.assisted&&!a.physical).length} încercări fără ajutor · {lessons.filter(l=>mastered(l.id)).length} lecții stăpânite</p></div><button className="primary" onClick={()=>go('lessons')}>Exersează 5 minute<ArrowRight size={18}/></button></div><h2 className="section-title">Drumul tău</h2><div className="progress-list">{lessons.map(l=>{const attempts=data.attempts.filter(a=>a.lessonId===l.id);return <button key={l.id} onClick={()=>start('learn',l.id)}><span className={`progress-check ${attempts.length?'done':''}`}>{attempts.length?<Check size={20}/>:<Target size={20}/>}</span><span><strong>{l.title}</strong><small>{mastered(l.id)?'Stăpânit în sesiuni diferite':attempts.length?`${attempts.length} încercări · Mai exersăm fără ajutor`:'Încă nedescoperit'}</small></span><ChevronRight size={19}/></button>})}</div><p className="small-caption">O lecție devine „stăpânită” după reușite fără ajutor în cel puțin două sesiuni. Vizionările nu se numără. Practica fizică este confirmată de tine.</p><div className="records"><h2>Rezolvările tale</h2>{!data.solves.length?<p>Prima rezolvare completă va apărea aici.</p>:data.solves.slice(-8).reverse().map((s,i)=><div className="record-row" key={`${s.at}-${i}`}><Box size={19}/><span>{s.physical?'Cub real':'Cub pe ecran'}<small>{new Date(s.at).toLocaleDateString('ro-RO')}{s.assisted?' · Cu ajutor':''}{s.interrupted?' · Întrerupt':''}</small></span><strong>{s.durationMs?clock(s.durationMs):'Fără timp'}</strong></div>)}</div></>}
  {screen==='parents'&&<><button className="back-link" onClick={()=>go('home')}><ArrowLeft size={17}/>Înapoi acasă</button><div className="page-heading"><span className="eyebrow">UN COLȚ PENTRU ADULȚI</span><h1>Pentru părinți.</h1><p>Sunet, instalare și un loc sigur pentru progres.</p></div><div className="settings-grid"><section className="settings-card"><span className="mode-icon blue-bg"><Volume2/></span><h2>O voce care îl însoțește</h2><p>Explicațiile rămân mereu vizibile. Sunetul începe după o atingere.</p><button className="secondary" onClick={async()=>{const result=await narration.speak('Salut, Erik! Învățăm împreună, pas cu pas.','welcome',data.preferences.slow);setAudioStatus(result==='unavailable'?narration.status().message:'Vocea este pregătită pentru lecții.')}}><Volume2 size={19}/>Testează vocea română</button><p className="small-caption">{audioStatus||narration.status().message}</p><div className="settings-toggles"><button onClick={()=>pref('muted')}>{data.preferences.muted?<VolumeX size={17}/>:<Volume2 size={17}/>}Sunet {data.preferences.muted?'oprit':'pornit'}</button><button onClick={()=>pref('slow')}>Ritm {data.preferences.slow?'lent':'normal'}</button></div></section>
   <section className="settings-card"><span className="mode-icon teal-bg"><Download/></span><h2>Pregătit de drum</h2><p>{offline?'Aplicația și lecțiile sunt descărcate pe acest dispozitiv.':'La prima vizită online, aplicația descarcă lecțiile și resursele pentru practica offline.'}</p><button className="secondary" onClick={async()=>{const ready=await verifyOffline();setOffline(ready);setNotice(ready?'Pachetul aplicației este disponibil offline. Dacă dispozitivul eliberează spațiu, poate fi nevoie de o nouă descărcare.':'Pachetul nu este încă pregătit. Rămâi online până se încheie descărcarea, apoi reîncarcă și verifică.');await requestPersistentStorage()}}><Download size={18}/>Verifică pachetul offline</button><p className="small-caption">O voce a sistemului poate avea nevoie de internet. Fișierele audio incluse sunt disponibile offline după descărcare.</p>{update&&<button className="text-button" onClick={()=>setModal({title:'Instalăm actualizarea?',text:'Progresul este păstrat. Aplicația se va redeschide la pagina de început.',label:'Actualizează acum',action:async()=>{await saveChain.current;await applyUpdate()}})}>O actualizare este pregătită</button>}</section>
   <section className="settings-card wide"><span className="mode-icon peach-bg"><ShieldCheck/></span><h2>Progresul rămâne pe acest dispozitiv</h2><p>Fără cont și fără sincronizare automată. Exportă o copie pentru a muta progresul pe telefon sau tabletă. Ștergerea datelor browserului poate șterge și progresul.</p>{!parentOpen?<div className="parent-gate"><label>Doar pentru părinți: cât face 8 + 5?<input inputMode="numeric" value={parentAnswer} onChange={e=>setParentAnswer(e.target.value)} placeholder="Răspuns" aria-label="Răspuns pentru părinți"/></label><button className="secondary" onClick={()=>parentAnswer==='13'?setParentOpen(true):setNotice('Mai verifică răspunsul.')}><ShieldCheck size={18}/>Deschide copiile de siguranță</button></div>:<><div className="backup-actions">{backupDownload?<a className="secondary" style={{fontSize:'.8rem',fontWeight:800,textDecoration:'none'}} href={backupDownload.href} download={backupDownload.filename}><Download size={18}/>Exportă progresul</a>:<button className="secondary" disabled><Download size={18}/>{backupError?'Export indisponibil':'Pregătim copia…'}</button>}<button className="secondary" onClick={()=>fileInput.current?.click()}><Upload size={18}/>Importă o copie</button></div>{backupError&&<p className="audio-status" role="alert">{backupError}</p>}<input hidden ref={fileInput} type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importBackup(f);e.target.value=''}}/><p className="small-caption">Doriți să corectați un timp accidental? Puteți șterge ultima înregistrare.</p><button className="text-button" disabled={!data.solves.length} onClick={()=>setModal({title:'Ștergem ultimul timp?',text:'Doar ultima rezolvare înregistrată va fi eliminată. Lecțiile rămân păstrate.',label:'Șterge înregistrarea',action:()=>edit(d=>({...d,solves:d.solves.slice(0,-1)}))})}>Șterge ultima înregistrare</button></>}</section>
   <section className="settings-card wide install-card"><h2>Un loc pe ecranul principal</h2><div className="install-columns"><div><span className="pill">iPHONE & iPAD</span><h3>Deschide în Safari</h3><p>Apasă <strong>Partajează</strong>, apoi <strong>Adăugați la ecranul principal</strong>. Activează „Deschideți ca aplicație web”, dacă apare, și apasă „Adăugați”.</p></div><div><span className="pill">ANDROID</span><h3>Deschide în Chrome</h3><p>Deschide meniul <strong>⋮</strong> și alege <strong>Adaugă pe ecranul de pornire</strong> sau <strong>Instalează aplicația</strong>. Confirmă instalarea.</p></div><div><span className="pill">CALCULATOR</span><h3>La un clic distanță</h3><p>În Chrome sau Edge, folosește pictograma de instalare din bara de adrese. Aplicația funcționează și direct în browser.</p></div></div><p className="small-caption">Pe iPhone și iPad, datele din aplicația instalată pot fi separate de cele din browser. Exportă și importă o copie dacă este necesar.</p></section></div><div className="parent-sources"><h3>Despre lecții</h3><p>Explicații originale în română, cu exerciții verificate prin motorul cubului. Puncte de referință: <a href="https://jperm.net/3x3/cfop" target="_blank" rel="noreferrer">J Perm · CFOP</a> și <a href="https://www.cubeskills.com/" target="_blank" rel="noreferrer">CubeSkills</a>. Ajutorul de rezolvare general folosește cubejs; nu îl prezentăm drept explicație CFOP.</p></div>{notice&&<div className="notice-box" role="status">{notice}</div>}</>}
  </main>
  <nav className="main-nav" aria-label="Navigare principală">{nav.map(n=>{const Icon=n.icon;const active=screen===n.id||(n.id==='play'&&screen==='session');return <button className={active?'active':''} key={n.id} onClick={()=>n.id==='play'?(current?.mode==='free'?go('session'):start('free')):go(n.id as Screen)}><Icon size={21}/><span>{n.label}</span></button>})}</nav>
  {modal&&<div className="modal-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button className="dialog-close icon-button" aria-label="Închide" onClick={()=>setModal(null)}><X/></button><span className="mode-icon blue-bg"><CircleHelp/></span><h2 id="dialog-title">{modal.title}</h2><p>{modal.text}</p><button className="primary" onClick={()=>{const action=modal.action;setModal(null);action()}}>{modal.label}</button><button className="text-button" onClick={()=>setModal(null)}>Păstrează poziția</button></section></div>}
  {help&&<div className="modal-backdrop"><section className="dialog help-dialog" role="dialog" aria-modal="true" aria-labelledby="help-title"><button className="dialog-close icon-button" aria-label="Închide ajutorul" onClick={()=>setHelp(false)}><X/></button><span className="mode-icon teal-bg"><Hand/></span><h2 id="help-title">{current?.mode==='physical'?'Hai să regăsim poziția.':'Tu controlezi cubul.'}</h2>{current?.mode==='physical'?<><p>1. Verifică centrele: galben sus, verde în față, roșu la dreapta.</p><p>2. Dacă ai ratat doar ultima mișcare, închide acest ajutor și folosește „Înapoi un pas”. Aplicația îți cere să faci mișcarea inversă pe cubul real.</p><p>3. Dacă poziția nu mai este clară, rezolvă cubul cu metoda pe care o știi. Apoi refacem pregătirea de la început.</p><button className="primary" onClick={()=>{setHelp(false);changeActive(a=>({...activity('physical',a.lessonId),phase:'physical-orient'}))}}>Voi porni de la un cub rezolvat</button><small>Acest buton schimbă doar modelul de pe ecran. Cubul real îl rezolvi tu.</small></>:<><p><strong>Întoarce o față:</strong> atinge-o și folosește „Orar”, „Invers” sau „Jumătate”. Poți glisa pe față: spre dreapta pentru orar, spre stânga pentru invers. Mișcările mici și glisările verticale nu o întorc.</p><p><strong>Privește din alt unghi:</strong> activează „Privește cubul”, apoi trage. Se schimbă numai vederea.</p><p><strong>Te-ai încurcat?</strong> Folosește „Înapoi”. Indiciul se calculează pentru poziția de acum. Reluarea exercițiului îți cere confirmare.</p><button className="primary" onClick={()=>setHelp(false)}>Am înțeles<Check size={19}/></button></>}</section></div>}
 </div>;
}
